# Codespaces configuration
# This file defines the default configuration for GitHub Codespaces

# Use 4-core machine by default
machine_type: "standardLinux32gb"

# Enable prebuilds for faster startup
prebuild:
  template: true

# Set up environment variables
env:
  # Python settings
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

  # Jupyter settings
  JUPYTER_ENABLE_LAB: "yes"

  # UV settings
  UV_CACHE_DIR: "/tmp/uv-cache"

# Default ports to forward
forward_ports:
  - "8081" # AutoGen Studio
  - "8888" # Jupyter Lab
  - "8000" # Development server

# Default VS Code extensions
extensions:
  - "ms-python.python"
  - "ms-python.vscode-pylance"
  - "ms-toolsai.jupyter"
  - "ms-python.black-formatter"
  - "ms-python.flake8"

# Repository settings
repository_template: true
